version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - .:/var/www
    env_file:
      - ./.env
    depends_on:
      - db
    networks:
      - laravel

  webserver:
    image: nginx:stable
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - laravel

  node:
    image: node:20
    container_name: laravel-vite
    working_dir: /var/www
    command: sh -c "npm install --legacy-peer-deps && npm run dev"
    volumes:
      - .:/var/www
    ports:
      - "5173:5173"   # Vite dev server
    networks:
      - laravel

  db:
    image: postgres:15
    container_name: laravel-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - laravel

networks:
  laravel:

volumes:
  dbdata:
